### ISSUE TITLE
Readchar returning spaces when run asynchronously

### ISSUE THREAD

**Issue by Yourself1011** [magmax/python-readchar#55] opened 2020-08-01 23:20 UTC
I'm creating a game and I would like to make a pause function when the user presses "p", so I use threading to asynchronously run readchar. The issue is, when I do this, the text becomes deformed with extra spaces after each line.

Before readchar:
![image](https://user-images.githubusercontent.com/57602332/89112078-fce88300-d42b-11ea-8de6-601e7f46a66c.png)

After readchar:
![image](https://user-images.githubusercontent.com/57602332/89112086-1093e980-d42c-11ea-9104-59b7fd36ff76.png)

**Comment by insidewhy** [comment] 2020-11-18 06:50
hi @Yourself1011 my PR fixes this issue, see https://github.com/magmax/python-readchar/pull/54

**Comment by insidewhy** [comment] 2020-11-18 06:50
Also this is a duplicate of https://github.com/magmax/python-readchar/issues/53

**Comment by magmax** [comment] 2021-02-28 19:49
Already merged. Should be fixed at v3.0.1. Can you confirm it?

**Comment by shasheene** [comment] 2021-10-05 05:59
Writing this comment to note the fix was reverted in v3.0.4 https://github.com/magmax/python-readchar/pull/54

Installing v3.0.3 worked fine for my purposes though: https://pypi.org/project/readchar/3.0.3/

**Comment by Cube707** [comment] 2022-07-25 14:12
should be fixed in `v4.0.0`

**Closed by Cube707** 2022-07-25 14:12 UTC
